on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: The AWS account to deploy to.
        options:
        - DEV
        - INT
        - REF
        - PROD
        required: true
        default: REF
      run_tests:
        type: boolean
        description: Run smoke and e2e tests that require a dedicated queue and APIM proxy.
        default: true
  release:
    types: ["published"]

concurrency:
  group: ${{ inputs.environment }}-all-components

jobs:
  pre-build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - run: echo "Prebuild step complete"

  plan-and-deploy-component:
    strategy:
      max-parallel: 1
      matrix:
        component: ['mgmt', 'mesh', 'events']

    uses: ./.github/workflows/logic-test-child.yaml
    with:
      environment: ${{ inputs.environment }}
      component: ${{ matrix.component }}
      deploy_layers: ${{ matrix.component == 'mgmt' && true || false }} # Only deploy layers on the 1st cycle
      deploy_infra: true
      run_tests: ${{ (matrix.component == 'events' && inputs.run_tests) && true || false }} # Only run the tests at the end
